# Generated by Django 3.0.6 on 2020-05-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='Some User', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('original_file', models.CharField(blank=True, max_length=255, null=True)),
                ('compressed_file', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Story')),
            ],
        ),
    ]
